# .github/workflows/kubernetes-deploy-workflow.yml
name: Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]
    paths:
      - 'k8s/**'  # Se déclenche sur les modifications des fichiers dans le dossier k8s
  workflow_dispatch:  # Pour déclencher manuellement le workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl configuration
        run: |
          kubectl version --client
          echo "Attempting to connect to cluster..."
          kubectl get nodes || echo "Failed to connect to cluster"

      - name: Apply Kubernetes manifests
        run: |
          echo "Applying Kubernetes configurations..."
          kubectl apply -f k8s/kafka-statefulset.yml
          kubectl apply -f k8s/postgres-deployment.yml
          kubectl apply -f k8s/user-service.yml
          kubectl apply -f k8s/order-service.yml
          # Ou utilisez kustomize
          # kubectl apply -k k8s/

      - name: Verify deployment
        run: |
          echo "Verifying deployments..."
          kubectl rollout status deployment/user-service
          kubectl rollout status deployment/order-service
          echo "All deployments successfully rolled out!"