# .github/workflows/kubernetes-deploy-workflow.yml
name: Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]
    paths:
      - 'k8s/**'  # Se déclenche sur les modifications des fichiers dans le dossier k8s
  workflow_dispatch:  # Pour déclencher manuellement le workflow
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed
    branches: [main, master]

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Save original kubeconfig
        shell: powershell
        run: |
          if (!(Test-Path -Path "$HOME/.kube")) {
            New-Item -Path "$HOME/.kube" -ItemType Directory
          }
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KUBE_CONFIG }}")) | Out-File -FilePath "$HOME/.kube/config.original" -Encoding utf8

      - name: Setup kubeconfig with proxy
        shell: powershell
        run: |
          # Start kubectl proxy using the original config
          Start-Process -FilePath "kubectl" -ArgumentList "proxy", "--port=8080", "--kubeconfig=$HOME/.kube/config.original" -NoNewWindow
          
          # Give proxy time to start
          Start-Sleep -Seconds 5
          
          # Create a simplified kubeconfig for using the proxy
          @"
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: http://localhost:8080
            name: minikube
          contexts:
          - context:
              cluster: minikube
              user: minikube
            name: minikube
          current-context: minikube
          users:
          - name: minikube
            user: {}
          "@ | Out-File -FilePath "$HOME/.kube/config" -Encoding ascii

      - name: Verify kubectl configuration
        shell: powershell
        run: |
          kubectl version --client
          Write-Host "Attempting to connect to cluster..."
          try {
            kubectl get nodes
          } catch {
            Write-Host "Failed to connect to cluster"
          }

      - name: Apply Kubernetes manifests
        shell: powershell
        run: |
          Write-Host "Applying Kubernetes configurations..."
          #kubectl apply -f k8s/kafka-statefulset.yml
          #kubectl apply -f k8s/postgres-deployment.yml
          #kubectl apply -f k8s/user-service.yml
          #kubectl apply -f k8s/order-service.yml
          #kubectl apply -f k8s/ingress.yml
          # Ou utilisez kustomize
          kubectl apply -k k8s/

      - name: Force redeploy services
        shell: powershell
        run: |
          Write-Host "Forcing redeployment to ensure new images are used..."
          kubectl rollout restart deployment/user-service
          kubectl rollout restart deployment/order-service

      - name: Verify deployment
        shell: powershell
        run: |
          Write-Host "Verifying deployments..."
          kubectl rollout status deployment/user-service
          kubectl rollout status deployment/order-service
          Write-Host "All deployments successfully rolled out!"